name: gauth-li
services:
  app:
    build:
      context: .
      args:
        BASE_URL: ${BASE_URL}
        CONNECTION_STRING: ${CONNECTION_STRING}
    volumes:
      - /usr/src/app/server/node_modules
    ports:
      - ${PORT:-3000}:3000
    environment:
      - TZ=Europe/Paris
      - CONNECTION_STRING=${CONNECTION_STRING}
      - APP_BASE_URL=${BASE_URL}
    restart: unless-stopped